### ISSUE TITLE
Rspamd with Træfik 

### ISSUE THREAD

**Issue by cypriotxx** [gw0/docker-dovecot-getmail#1]
is there any chance you can tell us how to integrate this with Rspamd ? with Træfik  ?

**Comment by gw0** [comment]
Huh, a spam filter can be added with a local mail server and then you deliver emails to it. Unfortunately, this is out-of-scope for the purpose of this project and would also consume more resources.

In my opinion it makes more sense to have a complete mail server in for this, because it is a more typical setup and you will find more examples and documentation on the internet.
